syntax = "proto3";

import "AiGameInfo.proto";
import "AichatBotCard.proto";
import "AlaLiveInfo.proto";
import "Anti.proto";
import "BannerList.proto";
import "BdtSearchInfo.proto";
import "BottomBar.proto";
import "BottomGameBar.proto";
import "CommentOverlayInfo.proto";
import "CommentPublisherConfig.proto";
import "FeedKV.proto";
import "FloorFoldInfo.proto";
import "ForumBotInfo.proto";
import "ForumRuleStatus.proto";
import "ForumShopGoodsInfo.proto";
import "GameDetail.proto";
import "GuideWordList.proto";
import "InputHintItem.proto";
import "InteractInfo.proto";
import "JumpLinkInfo.proto";
import "ManagerElection.proto";
import "MutliAichatBotCard.proto";
import "Page.proto";
import "PageGuidTips.proto";
import "PbList/AdFilter.proto";
import "PbList/AiChatCard.proto";
import "PbList/BawuDeleteReasonItem.proto";
import "PbList/BreadcrumbNavigation.proto";
import "PbList/FloatingIcon.proto";
import "PbList/PbGamePop.proto";
import "PbList/PbSortType.proto";
import "PbList/SettingInfo.proto";
import "PbList/SimilarContent.proto";
import "Post.proto";
import "PushFeedbackInfo.proto";
import "RecomTopicList.proto";
import "SimpleForum.proto";
import "SpriteShowStrategy.proto";
import "TabInfo.proto";
import "TailRecommendInfo.proto";
import "ThemeColorInfo.proto";
import "ThreadAlbumManage.proto";
import "ThreadInfo.proto";
import "User.proto";
import "WebviewData.proto";

message DataRes {
    ThreadInfo thread = 1;
    SimpleForum forum = 2;
    Anti anti = 3;
    User user = 4;
    repeated User user_list = 5;
    Post first_floor = 6;
    repeated Post post_list = 7;
    Page page = 8;
    repeated PbSortType pb_sort_info = 9;
    int32 sort_type = 10;
    repeated TabInfo tab_info = 11;
    TabInfo current_tab = 12;
    string partial_visible_toast = 13;
    string fold_tip = 14;
    int32 is_black_white = 15;
    int32 pb_notice_type = 16;
    string pb_notice = 17;
    int32 has_fold_comment = 18;
    int64 fold_comment_num = 19;
    repeated SimpleForum from_forum_list = 20;
    int64 thread_freq_num = 21;
    SimpleForum display_forum = 22;
    string multi_forum_text = 23;
    BannerList banner_list = 24;
    int32 show_adsense = 25;
    int32 ad_show_select = 26;
    int32 is_purchase = 27;
    GameDetail bottom_toast = 28;
    BreadcrumbNavigation breadcrumb_navigation = 29;
    PbGamePop pb_game_pop = 30;
    GameDetail game_detail = 31;
    SpriteShowStrategy sprite_show_strategy = 32;
    AlaLiveInfo recom_ala_info = 33;
    SimilarContent similar_content = 34;
    ManagerElection manager_election = 35;
    ForumRuleStatus forum_rule = 36;
    BawuDeleteReasonItem bawu_delete_reason = 37;
    repeated AiChatCard aichat_card = 38;
    AichatBotCard aichat_bot_card = 39;
    PushFeedbackInfo push_feedback_info = 40;
    string return_page = 41;
    FloatingIcon floating_icon = 42;
    repeated RecomTopicList thread_topic = 43;
    JumpLinkInfo jump_link_info = 44;
    repeated GuideWordList guide_word_list = 45;
    repeated string limit_dialog_name = 46;
    repeated InputHintItem input_hint = 47;
    ThreadAlbumManage thread_album_manage = 48;
    repeated FeedKV log_param = 49;
    WebviewData webview_data = 50;
    AdFilter ad_filter = 51;
    int32 is_official_forum = 52;
    MutliAichatBotCard mutli_aichat_bot_card = 53;
    ForumBotInfo forum_bot_info = 54;
    SettingInfo setting_info = 55;
    repeated ThemeColorInfo bottom_resource = 56;
    ForumShopGoodsInfo shop_goods_info = 57;
    int32 use_hybrid_pb = 58;
    BottomBar bottom_bar = 59;
    InteractInfo interact_info = 60;
    BdtSearchInfo bdt_search_info = 61;
    AiGameInfo ai_game_info = 62;
    int32 is_exclusive = 63;
    BottomGameBar bottom_game_bar = 64;
    PageGuidTips page_guid_tips = 65;
    CommentOverlayInfo comment_overlay_info = 66;
    FloorFoldInfo floor_fold_info = 67;
    TailRecommendInfo tail_recommend_info = 68;
    string no_more_show_text = 69;
    string fold_comment_show_text = 70;
    CommentPublisherConfig comment_publisher_config = 71;
}
